---
dist: xenial
sudo: required
language: python

env:
  - DOCKER_COMPOSE_VERSION=1.24.0

services:
  - docker


# Install an up to date (ish) docker-compose
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python-dev
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository --yes --update ppa:ansible/ansible
  - sudo apt-get install ansible
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo useradd -m metacpan -g users -G docker

before_script:
  - ansible --version | grep "python version"

script:
  - ansible-galaxy install --roles-path ./galaxy -r requirements.yml
  - ansible-playbook -i inventories/ansible_test tests/deploy_docker_mgmt.yml --syntax-check
  - ansible-playbook -i inventories/ansible_test tests/deploy_docker_mgmt.yml
  - idempotence=$(mktemp)
  - >
    sudo ansible-playbook -i inventories/ansible_test tests/deploy_docker_mgmt.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
