---

reboot: true

docker_mgmt:
  directory: /home/metacpan/docker-production
  git:
    repo: https://github.com/metacpan/metacpan-docker-production
    version: master
    user: metacpan

environments:
  github-meets-cpan: |
    GH_CPAN_SITE_PORT=5002
