---

- name: Fetch codebase
  git:
    repo: "{{ docker_mgmt.git.repo }}"
    dest: "{{ docker_mgmt.directory }}"
    depth: 1
    force: yes
    version: "{{ docker_mgmt.git.version }}"
  become: yes
  become_user: "{{ docker_mgmt.git.user }}"
