---

- name: "{{ site }} -- Set environment variables"
  set_fact:
    _compose_environment: >-
      env {{ environments[ site ] | default('') | regex_replace("\n", ' ') }}
  when: environments is defined and environments[ site ] is defined

- name: "{{ site }} -- Compose Up"
  # The -d is very important here, otherwise `docker-compose` starts in the
  # foreground and the whole process waits.
  shell: >-
    {{ _compose_environment | default('') }}
    /usr/local/bin/docker-compose up
    -d {{ site | mandatory }}
  args:
    chdir: "{{ docker_mgmt['directory'] | mandatory }}"
  become: yes
  become_user: "{{ metacpan_user | default(docker_mgmt.git.user) }}"
