---

# create environment file
- include_tasks: configure.yml

- name: "{{ site }} -- Setup containers with latest"
  docker_compose:
    project_src: "{{ docker_mgmt['directory'] }}"
    pull: true
    services: "{{ site }}"
  become: true
  become_user: root
