# vim: set filetype=ansible.yaml:
---

- hosts: hound_metacpan
  environment:
    MC_CONF_PRIVATE_DIR: "{{ grep_repo }}"
  vars:
    site: hound
  vars_files:
    - ../vars/settings.yml
  tasks:
    - name: Deploy hound site | checkout grep git repository
      git:
        clone: True
        repo: "{{ github_repo }}"
        version: master
        dest: "{{ grep_repo }}"
      become: True
      become_user: metacpan

    - name: Deploy hound site | define volume for git repository
      docker_volume:
        name: metacpan_git_shared
        driver_options:
          type: none
          device: "{{ grep_repo }}"
          o: bind
      become: True
      become_user: root

    - name: Deploy hound site | deploy site
      include_role:
        name: deploy_site

    - name: Create cron entries for shared git
      cron:
        name: update data
        cron_file: metacpan_git_shared
        user: "{{ metacpan_user | default(docker_mgmt.git.user) }}"
        special_time: hourly
        job: "cd {{ grep_repo }} && git pull origin master > /dev/null 2>&1"
      become: yes
      become_user: root
